## Function and Iterators

A function is defined to deploy an application, with default values for its version and namespace. How can you call this function to deploy the app in the 'staging' namespace while using the default version?

In [2]:
def deploy_app(app_name, version='1.0.0', namespace='default'):
    print(f"Deploying {app_name} v{version} to {namespace} namespace.")

deploy_app('auth-service', namespace="staging")    

Deploying auth-service v1.0.0 to staging namespace.


A script is mapping server names to their respective datacenter locations. What will be the output of this code?

In [3]:
servers = ['web-1', 'db-1', 'app-1', 'cache-1']
locations = ['us-east', 'us-west', 'eu-central']
 
for server, loc in zip(servers, locations):
    print(f"'{server}' is in '{loc}'")

'web-1' is in 'us-east'
'db-1' is in 'us-west'
'app-1' is in 'eu-central'


A script needs to display a numbered list of pending software updates. Which code snippet correctly uses enumerate to produce a numbered list starting with "1." for the first item, and incrementing the number by one for each item of the following list?



updates = ['kernel-patch', 'openssl-fix', 'python-update']

In [5]:
updates = ['kernel-patch', 'openssl-fix', 'python-update']
for i, update in enumerate(updates, start=1):
    print(f"{i}: {update}")

1: kernel-patch
2: openssl-fix
3: python-update


The function below is intended to report on a list of tasks without changing the original list. However, after the function call, the pending_deploys list is empty. What is the cause of this bug, and how should it be fixed?

In [ ]:
def report_tasks(task_list):
    print("Tasks to process:")
    while task_list:
        task = task_list.pop(0)
        print(f"- {task}")
    print("Report complete.")
 
pending_deploys = ['deploy-web', 'deploy-db', 'deploy-cache']
report_tasks(pending_deploys)
# This next line unexpectedly prints: "Tasks remaining: []"
print(f"Tasks remaining: {pending_deploys}")

The .pop(0) method is modifying the list passed to it. The fix is to create a copy of the list for processing, by changing the first line of the function to task_list = task_list.copy().

## OOP in Python

When defining a Python class to represent a server, what is the primary role of the __init__ method?

Answer: It is a method that is automatically called when an instance of the class is created, used to initialize the instance's unique attributes(for example, self.hostname = "web01")

A WebServer class inherits from a generic Server class. Both classes have a shutdown() method. How can the WebServer's shutdown() method first perform its own specific actions and then call the generic shutdown logic from the Server class?

In [ ]:
class WebServer(Server):
    def shutdown(self):
        print("Shutting down web server.")
        super().shutdown()

What is the fundamental difference between an instance attribute (e.g., self.hostname) and a class attribute?

In [ ]:
class Server:
    # Class attribute
    location = "US-EAST-1"
 
    def __init__(self, hostname):
        # Instance attribute
        self.hostname = hostname

A class attribute is shared by all instances of the class, while an instance attribute is unique to each specific object.
All objects created from the Server class will share the single location attribute. However, each object will have its own distinct hostname attribute, set when the object is created.

Two instances of a User class are created. What will be the output of the final print statement?



In [6]:
class User:
    def __init__(self, username):
        self.username = username
        self.is_active = False
 
    def activate(self):
        self.is_active = True
 
user1 = User("admin")
user2 = User("guest")
user1.activate()
 
print(f"{user1.username}: {user1.is_active}, {user2.username}: {user2.is_active}")

admin: True, guest: False


An engineer wrote a class to monitor services. When they create an instance and check its status, they get an AttributeError. What is the cause of this bug?

In [ ]:

class ServiceMonitor:
    def __init__(self, service_name):
        name = service_name
        is_alive = False
 
    def check_status(self):
        print(f"Checking status of {self.name}...")
        self.is_alive = True
        return self.is_alive
 
monitor = ServiceMonitor("database")
monitor.check_status()

The __init__ method created local variables name and is_alive instead of instance attributes. The fix is to use self.name= service_name and self.is_alive=False.

Consider the following class definition. What is the output of the code?

In [7]:
class VM:
    # Class attribute
    hypervisor = "KVM"
 
    def __init__(self, name):
        self.name = name
 
vm1 = VM("web-01")
vm2 = VM("db-01")
 
# The hypervisor for all VMs is upgraded
VM.hypervisor = "Xen"
 
print(f"{vm1.name} on {vm1.hypervisor}, {vm2.name} on {vm2.hypervisor}")

web-01 on Xen, db-01 on Xen


A child class DatabaseServer is created from a parent Server class. What is the correct way to initialize both the parent's attributes (hostname) and the child's specific attribute (db_engine)?

In [ ]:
class DatabaseServer(Server):
    def __init__(self, hostname, db_engine):
        super().__init__(hostname)
        self.db_engine = db_engine

## Working with Flexible arguements

A function is designed to gather system metrics, where some metrics are required and others are optional. What is the value of the extra_metrics dictionary inside the function?

In [ ]:
def gather_metrics(hostname, *base_metrics, **extra_metrics):
    # What is the value of extra_metrics?
    pass
 
gather_metrics("web01", "cpu_usage", "mem_usage", disk_io=45.5, network_traffic="200MB/s")

{'disk_io': 45.5, 'network_traffic' : '200MB/s'} 
**extra_mtrics collects all keyword arguements  that are not explicitly defined as parameters. In this call, disk_io and network_traffic are passed as keyword arguements and are therefore collected into the extra_metrics dictionary.

Q: A function is defined to accept a variable number of file paths to process. What is the value and data type of the paths variable inside the function?

In [ ]:
def process_files(*paths):
    # What is `paths` here?
 
process_files("/etc/hosts", "/etc/nginx/nginx.conf")

A: It is a tuple contatining ("/etc/hosts", "/etc/nginx/nginx.conf"). The *syntax in a function definition gathers all provided arguements into a single tuple paths to maintain the order.

Q: A function needs to be called with configuration settings stored in a dictionary. What is the correct syntax to unpack the db_config dictionary into keyword arguments for the connect_to_db function?

In [ ]:

def connect_to_db(host, port, user, password):
    print(f"Connecting to {host}:{port} as {user}...")
 
db_config = {'host': 'db.prod', 'port': 5432, 'user': 'admin', 'password': '123'}

A: connect_to_db(**db_config)

Q: An engineer wants to create a flexible function that takes a required command and optional keyword arguments for flags. The code below, however, raises a TypeError. What is the cause of the error?

In [ ]:

def run_command(command, **options):
    option_str = " ".join([f"--{k}={v}" for k, v in options.items()])
    print(f"Executing: {command} {option_str}")
 
run_command("deploy", "app-server", verbose=True)

The string "app-server" is passed as a positional arguement

Q: In what order must the different types of parameters appear in a Python function definition?

A: Standard positional arguements, *args, keyowrd-only arguements, **kwargs

Q: A function is called by unpacking a list of values. What will be the output?

In [ ]:

def check_health(host, port, timeout):
    print(f"Checking {host} on port {port} with a {timeout}s timeout.")
 
params = ["api.service.local", 443, 10, "extra_value"]
check_health(*params)

A: A TypeError is raised because the params list contains more items than the function has parameters

Q: A function is designed to merge multiple configuration dictionaries. The first dictionary provides base settings, and subsequent dictionaries provide overrides. What will be the final value of final_config?

In [8]:

def merge_configs(base_config, *override_configs):
    merged = base_config.copy()
    for config in override_configs:
        merged.update(config)
    return merged
 
config1 = {'user': 'admin', 'retries': 3}
config2 = {'retries': 5, 'timeout': 30}
config3 = {'timeout': 60, 'loglevel': 'debug'}
 
final_config = merge_configs(config1, config2, config3)

In [10]:
print(final_config)

{'user': 'admin', 'retries': 5, 'timeout': 60, 'loglevel': 'debug'}


## Generator Quiz

Question 1:
Consider the following Python code. What will be printed to the console when it is executed?

In [ ]:
def generate_reports(count):
    print("Initializing report generator...")
    for i in range(count):
        yield f"Report #{i+1}"
    print("All reports generated.")
 
reports_generator = generate_reports(3)
print("Generator created.")

Generator created
 The body of a generator function does not execute when the function is called. Instead, a generator object is created and returned immediately. The code inside the generate_reports function (including the print statements) will only run when the generator is iterated over (e.g., with next() or a for loop).



Question 2:
What is the output of the following code snippet?

In [1]:
def sequence_generator():
    value = 10
    print(f"Yielding {value}")
    yield value
 
    value += 5
    print(f"Yielding {value}")
    yield value
 
    value *= 2
    print(f"Yielding {value}")
    yield value
 
gen = sequence_generator()
next(gen)
val = next(gen)
print(f"Final value: {val}")

Yielding 10
Yielding 15
Final value: 15


The first next(gen) call starts the generator; it prints "Yielding 10" and yields 10, then pauses. The second next(gen) call resumes execution; value is incremented to 15, "Yielding 15" is printed, and 15 is yielded and assigned to val. The program then prints the final line. The code for the third yield is never reached.

Question 3:
A developer wrote the following script to create pairs of network zones. They expected to see all possible pairs (e.g., "Web:DB", "Web:API", "DB:Web", etc.), but the output was not what they expected. What is the bug, and how should it be fixed in the most efficient way?

In [ ]:
def get_zones():
    yield "Web"
    yield "DB"
    yield "API"
 
zones_gen = get_zones()
 
for zone1 in zones_gen:
    for zone2 in zones_gen:
        print(f"{zone1}:{zone2}")

The bug is that the zones_gen generator is exhausted by the inner loop on its first run. The fix is to get a fresh generator for the inner loop by calling the factory function again: for zone2 in get_zones():.

This is the correct answer. The inner loop for zone2 in zones_gen: completely consumes the generator. When the outer loop starts its second iteration (e.g., with zone1 as "DB"), the zones_gen is already empty (exhausted), so the inner loop does not run again. Creating a new generator for each loop (for zone1 in get_zones(): and for zone2 in get_zones():) ensures each loop works with a fresh, independent iterator.

Question 4:
What will be the output of this Python script, which attempts to iterate over a generator twice?

In [2]:
def device_ids():
    yield "sensor-A"
    yield "sensor-B"
 
ids = device_ids()
 
print("First pass:")
for device_id in ids:
    print(f"- {device_id}")
 
print("\nSecond pass:")
for device_id in ids:
    print(f"- {device_id}")

First pass:
- sensor-A
- sensor-B

Second pass:


This is the correct answer. The first for loop consumes all the values from the ids generator, exhausting it. When the second for loop attempts to iterate over the same exhausted generator, the generator immediately signals it has no more items (by raising StopIteration internally, which the for loop handles), so the loop's body never executes.

Question 5:
A generator function is defined to yield a sequence of status messages. What is the exact output when the following code is run?

In [3]:
def deployment_status():
    status = "PENDING"
    yield status
 
    status = "IN_PROGRESS"
    yield status
 
    status = "COMPLETED"
    print(f"Final state: {status}")
 
d_status = deployment_status()
print(f"1: {next(d_status)}")
print(f"2: {next(d_status)}")
try:
    next(d_status)
except StopIteration:
    print("3: Deployment finished.")

1: PENDING
2: IN_PROGRESS
Final state: COMPLETED
3: Deployment finished.


This is the correct answer. The first two next() calls consume the first two yielded values. The third next() call resumes the generator. It executes the print(f"Final state: {status}") line, then the function finishes, which causes a StopIteration to be raised. The except block catches this and prints its message.

## Building Lazy pipelines with Generators

Question 1:
A DevOps engineer needs to process a 50 GB log file to count the number of lines containing the word "FATAL". The engineer's machine has only 8 GB of RAM. Which of the following statements best explains the primary advantage of using a lazy generator pipeline for this task?

Answer: 
The pipeline avoids loading the entire 50 GB file into memory at once. It processes the file line-by-line, keeping memory usage minimal and constant regardless of the file size.

Correct! This is the core benefit of lazy pipelines. By reading and processing the file one line at a time, the memory footprint remains extremely low. The entire 50 GB file is never held in RAM, making it possible to process on a machine with much less memory.

Question 2:
You are given a pipeline of generators to process a list of raw transaction data. What will be the final output of the following script?

In [1]:
def parse_transactions(data):
    print("Parsing...")
    for item in data:
        parts = item.split(':')
        yield (parts[0], int(parts[1]))
 
def filter_high_value(transactions, min_value=100):
    print("Filtering...")
    for _, amount in transactions:
        if amount >= min_value:
            yield amount
 
def apply_fees(amounts, fee_percent=10):
    print("Applying fees...")
    for amount in amounts:
        yield amount - (amount * fee_percent / 100)
 
raw_data = ["TX01:50", "TX02:200", "TX03:150", "TX04:90"]
 
pipeline = apply_fees(filter_high_value(parse_transactions(raw_data)))
 
result = list(pipeline)
print(result)

Applying fees...
Filtering...
Parsing...
[180.0, 135.0]


Correct. The list() constructor pulls items one by one through the entire pipeline. The print statements inside the generators are executed only when the pipeline is first consumed at each stage. parse_transactions yields ('TX02', 200), which filter_high_value yields as 200, and apply_fees yields as 180.0. This repeats for 150, which becomes 135.0. The other items are filtered out.

Question 3:
The following script is intended to first iterate through all "login" events to perform an action (simulated by the print statement) and then, in a separate step, count the total number of these events. However, the script contains a bug and reports an incorrect count of 0. What is the fundamental cause of this bug, and what is the most suitable solution to fix it while preserving the two-step logic?

In [ ]:
def get_login_events(all_events):
    for event in all_events:
        if event.get("type") == "login":
            print(f"Found login for user: {event['user_id']}")
            yield event
 
events = [
    {"user_id": 101, "type": "login"},
    {"user_id": 102, "type": "page_view"},
    {"user_id": 103, "type": "login"},
    {"user_id": 104, "type": "logout"},
    {"user_id": 105, "type": "login"},
]
 
login_stream = get_login_events(events)
 
# Step 1: Perform an action on each login event
for _ in login_stream:
    pass
 
# Step 2: Count the total number of login events
count = len(list(login_stream))
print(f"Total logins: {count}") # Buggy output: Total logins: 0

Cause: The login_stream generator is exhausted after the first for loop. A generator can only be iterated over once.
Solution: Convert the generator to a list at the beginning and perform both operations on that reusable list.



Correct. This choice accurately identifies generator exhaustion as the root cause. The proposed solution is the most practical fix for scenarios requiring multiple passes over the same dataset. It eagerly evaluates the generator into a list, which can then be used repeatedly without issue.

Question 4:
Consider this two-stage pipeline designed to process a sequence of numbers. What is the exact sequence of printed output when this script is executed?

In [2]:
def number_source(n):
    print("SOURCE: Starting")
    for i in range(n):
        print(f"SOURCE: Yielding {i}")
        yield i
    print("SOURCE: Finished")
 
def doubler(items):
    print("DOUBLER: Starting")
    for item in items:
        print(f"DOUBLER: Processing {item}")
        yield item * 2
    print("DOUBLER: Finished")
 
pipeline = doubler(number_source(2))
print("--- Getting first item ---")
print(f"Result: {next(pipeline)}")
print("--- Getting second item ---")
print(f"Result: {next(pipeline)}")

--- Getting first item ---
DOUBLER: Starting
SOURCE: Starting
SOURCE: Yielding 0
DOUBLER: Processing 0
Result: 0
--- Getting second item ---
SOURCE: Yielding 1
DOUBLER: Processing 1
Result: 2


Correct. This output accurately traces the lazy, "pull-based" execution. The call to next(pipeline) pulls a value from doubler, which in turn pulls a value from number_source. The first item 0 is yielded from source, processed by doubler, and returned as 0. The second call to next resumes the process, pulling 1 from source, which is processed by doubler and returned as 2.

Question 5:
The following script is intended to create a lazy pipeline that identifies IP addresses that transferred more than 1000 bytes and then formats them for a report. However, the filter_heavy_hitters function breaks the lazy evaluation model. How should the filter_heavy_hitters function be rewritten to ensure the entire pipeline is lazy and memory-efficient?

In [ ]:
def parse_logs(log_lines):
    for line in log_lines:
        parts = line.split()
        if len(parts) == 2:
            yield (parts[0], int(parts[1]))
 
def filter_heavy_hitters(records):
    # This function is not lazy
    results = []
    for ip, byte_count in records:
        if byte_count > 1000:
            results.append(ip)
    return results # Eagerly returns a list
 
def format_for_report(ip_addresses):
    for ip in ip_addresses:
        yield f"ALERT: High traffic from {ip}"
 
# How the pipeline is used:
logs = ["1.1.1.1 500", "2.2.2.2 2500", "3.3.3.3 4000"]
records_gen = parse_logs(logs)
heavy_ips = filter_heavy_hitters(records_gen) # Entire records_gen is consumed here
report_lines = format_for_report(heavy_ips)

def filter_heavy_hitters(records):
    for ip, byte_count in records:
        if byte_count > 1000:
            yield ip


Correct. By replacing the list-building logic with a for loop that yields values one by one, the function is transformed into a generator. This makes it lazy, processing one record at a time and passing it down the pipeline without building an intermediate list in memory.

Question 6:
An engineer is writing a helper function get_cloud_regions() that fetches a list of available cloud provider regions (for example, 'us-east-1', 'eu-west-2'). The list is small (fewer than 50 items), does not change during the program's execution, and needs to be referenced by multiple other functions throughout the application's lifecycle. Which approach is most suitable for this function and why?

Answer: 
Use a regular function that returns a list because the data is small and needs to be accessed repeatedly. Storing the result in a list is more practical than re-creating an exhausted generator.


Correct. For small, static datasets that need to be used more than once, the eager approach of returning a list (or tuple) is superior. The memory cost is trivial, and the resulting list can be reused, iterated over, and accessed by index freely, which is exactly what the scenario requires.

## Decorator Fundamentals and Best Practices

Question 1:
In DevOps automation, you often need to add logging to many different functions that deploy services, update configurations, or run backups. Which statement best describes the primary advantage of using a decorator for this purpose?

Answer: Decorators add functionality (a "cross-cutting concern" like logging or timing) to multiple functions without modifying each function's source code, thus avoiding code duplication.


Correct. This is the core purpose of a decorator. It allows you to define a common behavior (like logging) in one place and apply it cleanly to any number of functions using the @ syntax, adhering to the "Don't Repeat Yourself" (DRY) principle.

Question 2:
What is the exact output of the following script when it is executed?

In [ ]:
import functools
 
def state_change_decorator(func):
    @functools.wraps(func)
    def wrapper():
        print("State: Preparing to execute...")
        func()
        print("State: Execution complete.")
    return wrapper
 
@state_change_decorator
def apply_migrations():
    print("Action: Applying database migrations.")
 
apply_migrations()

State: Preparing to execute...
Action: Applying database migrations.
State: Execution complete.


Correct. The @state_change_decorator syntax means apply_migrations now refers to the wrapper function. When called, wrapper first prints its "before" message, then calls the original apply_migrations function, and finally prints its "after" message.

Question 3:
An engineer wrote a decorator to add a prefix to a function's string result. However, when the script runs, the final line prints Result from main script: None. What is the cause of the bug, and what is the correct fix?

In [ ]:
def add_prefix_decorator(func):
    def wrapper(*args, **kwargs):
        original_result = func(*args, **kwargs)
        prefixed_result = f"[PREFIX] {original_result}"
        print(f"Inside wrapper, prefixed result is: {prefixed_result}")
    return wrapper
 
@add_prefix_decorator
def get_hostname(server_id):
    return f"server-{server_id}.prod.local"
 
hostname = get_hostname(101)
print(f"Result from main script: {hostname}")

Answer:

Cause: The wrapper function calculates the prefixed_result but does not return it. Since the wrapper has no explicit return, it implicitly returns None.
Fix: Add return prefixed_result to the end of the wrapper function.



Correct. The wrapper function effectively replaces the original function. If the wrapper doesn't return a value, the caller will receive None. The fix is to ensure the wrapper returns the intended new value.


Question 4:
This script uses a dictionary as a dispatch table to execute an action based on a command string. This pattern relies on functions being "first-class citizens." What is the output of the script?

In [ ]:
def provision_vm(hostname):
    return f"PROVISION: Virtual machine {hostname} created."
 
def deprovision_vm(hostname):
    return f"DEPROVISION: Virtual machine {hostname} destroyed."
 
def reboot_vm(hostname):
    return f"REBOOT: Virtual machine {hostname} restarting."
 
action_map = {
    "create": provision_vm,
    "destroy": deprovision_vm,
    "restart": reboot_vm,
}
 
command = "create"
target = "db-main-01"
 
if command in action_map:
    # Look up the function and call it
    action_func = action_map[command]
    result = action_func(target)
    print(result)
else:
    print(f"Unknown command: {command}")

PROVISION: Virtual machine db-main-01 created.
Correct

Correct. The script looks up the key "create" in action_map, which returns the provision_vm function object. It then calls this function with the argument "db-main-01", and the string returned by that function is printed.

Question 5:
This decorator is designed to log details about a function call, including arguments and the return value. What will be printed to the console when this script is executed?

In [1]:
from functools import wraps
 
def audit_log(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        user = kwargs.get("user", "unknown")
        print(f"AUDIT: User '{user}' is calling '{func.__name__}' with args {args}.")
        value = func(*args, **kwargs)
        print(f"AUDIT: Call finished. Returned: {value}")
        return value
    return wrapper
 
@audit_log
def set_firewall_rule(rule_id, action="BLOCK", *, user="admin"):
    return {"status": "success", "rule_id": rule_id, "action": action}
 
# Function is called here
output = set_firewall_rule(101, user="dev-ops")

AUDIT: User 'dev-ops' is calling 'set_firewall_rule' with args (101,).
AUDIT: Call finished. Returned: {'status': 'success', 'rule_id': 101, 'action': 'BLOCK'}


Correct. The positional argument 101 is captured in args. The keyword argument user="dev-ops" is captured in kwargs, and kwargs.get("user") correctly retrieves it. The decorator prints its logs before and after calling the function, which uses its default value for action.

## Advanced Decorator Practices

Question 1:
What is the primary purpose and benefit of using @functools.wraps when creating a Python decorator?


It copies metadata (like __name__, __doc__, and the signature) from the original function to the wrapper function, which is crucial for introspection, documentation, and debugging.

Correct

Correct. Without @wraps, calling help() or accessing __name__ on a decorated function would show information about the inner wrapper function, not the original function. @wraps fixes this by making the wrapper "look" like the original function from the outside.

Question 2:
An engineer writes a decorator to log function calls, but forgets to use @functools.wraps. What will be the output when the following script inspects the decorated function's metadata?

In [2]:
def logging_decorator(original_function):
    def wrapper_function(*args, **kwargs):
        """This is the wrapper's docstring."""
        print(f"Calling function: {original_function.__name__}")
        return original_function(*args, **kwargs)
    return wrapper_function
 
@logging_decorator
def get_user_permissions(user_id: int) -> list:
    """Returns a list of permissions for a given user."""
    return ["admin", "editor"]
 
print(f"Function name: {get_user_permissions.__name__}")
print(f"Docstring: {get_user_permissions.__doc__}")

Function name: wrapper_function
Docstring: This is the wrapper's docstring.


Correct. Because @functools.wraps was not used, the decorated get_user_permissions variable now points directly to wrapper_function. Therefore, inspecting its __name__ and __doc__ attributes reveals the metadata of the wrapper, not the original function.

Question 3:
When designing a decorator, you realize you need to pass a configuration value to it at definition time, like so: @retry(attempts=5). Why is an extra layer of nesting (a "decorator factory") required to achieve this?


Because a standard decorator function is only allowed to accept the function it decorates. To accept other arguments, you must call a factory function that returns the actual decorator.

Correct

Correct. A plain decorator's signature is decorator(func). The @ syntax provides only that one argument (the function being decorated). The expression @retry(attempts=5) first calls retry(attempts=5), which must return the real decorator. That returned decorator then receives the function to be decorated. This three-layer structure (factory -> decorator -> wrapper) is necessary to handle configuration.

Question 4:
This script uses a configurable decorator require_role to protect a function. Given the decorator and the function call, what is the output?

In [3]:
from functools import wraps
 
CURRENT_USER = {"username": "prod-agent", "role": "viewer"}
 
def require_role(required_role):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if CURRENT_USER.get("role") == required_role:
                print("Permission granted.")
                return func(*args, **kwargs)
            else:
                print(f"Permission denied. Requires '{required_role}'.")
                return None
        return wrapper
    return decorator
 
@require_role(required_role="admin")
def deploy_service(service_name):
    print(f"Deploying service: {service_name}")
    return "SUCCESS"
 
result = deploy_service("user-database")
print(f"Final result: {result}")

Permission denied. Requires 'admin'.
Final result: None


Correct. The @require_role(required_role="admin") call configures the decorator to check for the "admin" role. The wrapper compares this to the CURRENT_USER's role ("viewer") and finds a mismatch. It then prints the denial message and returns None, which is then printed as the final result.

Question 5:
An engineer attempts to write a decorator factory with_context that adds a context dictionary to the decorated function's keyword arguments. However, the implementation is structurally incorrect. Which of the following implementations correctly fixes the structure of the with_context decorator factory?

In [ ]:
def with_context(func, context_data):
    def wrapper(*args, **kwargs):
        kwargs['context'] = context_data
        return func(*args, **kwargs)
    return wrapper
 
 
@with_context(context_data={"user_id": 123})
def process_request(request_id, *, context={}):
    print(f"Processing {request_id} for user {context['user_id']}")

def with_context(context_data):
    def decorator(func):
        def wrapper(*args, **kwargs):
            kwargs['context'] = context_data
            return func(*args, **kwargs)
        return wrapper
    return decorator
Correct

Correct. This code correctly implements the three-level structure. with_context(context_data) is the factory that accepts configuration. It returns decorator(func), which is the actual decorator that accepts the function. decorator in turn returns wrapper, which contains the runtime logic.

Question 6:
When stacking multiple decorators on a single function, the order in which they are listed matters. In which scenario is the order most critical and likely to cause bugs or unexpected behavior?

When one decorator transforms the return value (e.g., formats it as JSON) and another decorator needs to operate on that transformed value (e.g., logs the JSON string).

Correct

Correct. This is the most critical case. If a decorator expects a certain data type (e.g., a dictionary) but the decorator below it in the stack has already converted it to another type (e.g., a JSON string), a TypeError or AttributeError will occur. The execution order (top-down) means the outer decorator acts on the result of the inner decorator.

Question 7:
Two decorators, @log_enter and @log_exit, are stacked on a function. Based on the rules of decorator application and execution, what is the exact output printed to the console?

In [4]:
from functools import wraps
 
def log_enter(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("ENTERING")
        return func(*args, **kwargs)
 
    return wrapper
 
def log_exit(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)
        print("EXITING")
        return result
 
    return wrapper
 
@log_enter
@log_exit
def perform_task():
    print("  ...TASK RUNNING...")
 
perform_task()

ENTERING
  ...TASK RUNNING...
EXITING


Correct. Execution happens from the outside-in. The @log_enter decorator is outermost, so its wrapper runs first, printing "ENTERING". It then calls the next function in the chain (the one wrapped by @log_exit). The @log_exit wrapper calls the original perform_task, which prints "...TASK RUNNING...". Finally, the execution unwinds: the @log_exit wrapper prints "EXITING", and the call chain completes.

## Python Exception Handling: The Fundamentals

Question 1:
A DevOps engineer writes a Python function to check the status of a service endpoint. What is the exact output returned by the function call check_service_status(80)?

In [2]:
def check_service_status(port):
    print("Initiating check...")
    log = []
    try:
        if port == 80:
            log.append("OK")
        elif port == 503:
            raise ConnectionRefusedError("Service unavailable")
        else:
            log.append("Unknown")
    except ConnectionRefusedError:
        log.append("FAIL")
        print("Connection failed.")
    else:
        log.append("SUCCESS")
        print("Check completed without errors.")
    finally:
        log.append("LOGGED")
        print("Finalizing check.")
    return log

print(check_service_status(80))

Initiating check...
Check completed without errors.
Finalizing check.
['OK', 'SUCCESS', 'LOGGED']


Correct. When port is 80, the if port == 80: condition is met, and "OK" is appended. No exception is raised, so the except block is skipped. Because the try block completed without raising an exception, the else block is executed, appending "SUCCESS" and printing a message. The finally block always executes, appending "LOGGED" and printing its message. The final list returned is ['OK', 'SUCCESS', 'LOGGED'].

Question 2:
A script is being designed to process a list of hostnames. For each hostname, it will connect, download a configuration file, and parse it. The network is known to be unreliable, and some configuration files might be malformed or missing expected keys.

Which of the following best describes the most Pythonic and robust design philosophy for this script?

The EAFP (Easier to Ask for Forgiveness than Permission) approach, where the script directly attempts to connect, download, and parse the file inside a try block, using specific except blocks to handle ConnectionError, FileNotFoundError, or KeyError as they occur.

Correct

Correct. This is the preferred Pythonic approach for this scenario. It results in cleaner, more readable code by focusing the try block on the primary task (the "happy path"). It robustly handles specific, expected errors in separate except blocks, clearly separating the main logic from the error-handling logic.

Question 3:
You are reviewing a script that parses structured log data, which is represented as a list of dictionaries. What will be printed to the console when this script is executed?

In [3]:
def summarize_logs(log_entries):
    summary = []
    for entry in log_entries:
        try:
            # The 'user' key is optional
            user = entry.get('user', 'system')
            # The 'event_id' key is mandatory
            event_id = entry['event_id']
            summary.append(f"{event_id}:{user}")
        except KeyError:
            summary.append("ERROR:Missing-Data")
        except (TypeError, AttributeError):
            summary.append("ERROR:Invalid-Entry")
 
    return summary
 
logs = [
    {'event_id': 101, 'user': 'alice'},
    {'event_id': 102},
    None,
    {'user': 'bob'}
]
 
print(summarize_logs(logs))

['101:alice', '102:system', 'ERROR:Invalid-Entry', 'ERROR:Missing-Data']


Correct. The third entry None causes a TypeError when the code attempts entry.get(...), as NoneType has no .get method. The except TypeError block is triggered. Result: 'ERROR:Invalid-Entry'. The fourth entry {'user': 'bob'} causes a KeyError when the code attempts entry['event_id'], as this key is missing. The except KeyError block is triggered. Result: 'ERROR:Missing-Data'.

Question 4:
A junior developer wrote the following function to retrieve a specific metric from a nested dictionary representing server monitoring data. The function call returns "Could not retrieve metric 'memory' for server 'srv-db-01'." as expected. However, what is the most significant flaw in this function's error handling design?

In [4]:

def get_metric(data, server_id, metric_name):
    try:
        value = data[server_id][metric_name]
        return f"Metric '{metric_name}' on server '{server_id}' is {value}"
    except:
        return f"Could not retrieve metric '{metric_name}' for server '{server_id}'."
 
# Example usage:
server_data = {
    "srv-web-01": {"cpu": 0.75, "memory": 0.5},
    "srv-db-01": {"cpu": 0.4}
}
print(get_metric(server_data, "srv-db-01", "memory"))

Could not retrieve metric 'memory' for server 'srv-db-01'.



Using a bare except: clause is a bad practice because it catches all exceptions, including system-level ones and programming errors, making the code difficult to debug.

Correct

Correct. This is the most critical flaw. A bare except: (equivalent to except BaseException:) catches everything, including SystemExit, KeyboardInterrupt, and even SyntaxError. More importantly for a developer, it will silently hide unrelated bugs, such as a TypeError if data was accidentally passed as None. The handler should have been specific, like except KeyError:, to only catch the expected error of a missing key.

Question 5:
What is the primary conceptual difference between a ValueError and a TypeError in Python?


ValueError occurs when an operation receives an argument of the right type but an inappropriate value, whereas TypeError occurs when the argument's type itself is invalid for the operation.

Correct

This is the core distinction. For int("abc"), the int() function is given a str (the correct type), but the value "abc" is inappropriate. This is a ValueError. For len(123), the len() function is given an int, which is the wrong type entirely; it expects a sequence or collection. This is a TypeError.

## Raising and Defining custom exceptions in Python

Question 1:
You are writing a function get_user_profile(user_id) that fetches user data from a remote database. Under which circumstances is it most appropriate to raise an exception rather than return None?


When the database connection times out or is refused, the function should raise ConnectionError.

Correct

Correct. A connection failure is an unexpected, exceptional event that prevents the function from fulfilling its purpose. The function itself cannot resolve this issue. Raising an exception is the correct way to signal this failure to the caller, so it can be logged, retried, or handled appropriately at a higher level.

Question 2:
A function is written to validate a deployment configuration. Analyze its behavior with the given inputs. What is the output of this script?

In [5]:
def validate_config(config_data):
    if not isinstance(config_data, dict):
        raise TypeError("Configuration must be a dictionary.")
 
    mem_limit = config_data.get("memory_limit_mb")
    if mem_limit is None:
        raise ValueError("Mandatory key 'memory_limit_mb' is missing.")
 
    if not (isinstance(mem_limit, int) and 256 <= mem_limit <= 4096):
        raise ValueError(f"Memory limit {mem_limit} is outside the allowed range (256-4096).")
 
    print(f"Config valid: {mem_limit}MB")
 
 
configs = [
    {"memory_limit_mb": 1024},
    {"memory_limit_mb": 128},
    {"cpu_cores": 4},
    "memory_limit_mb: 512"
]
 
for config in configs:
    try:
        validate_config(config)
    except (ValueError, TypeError) as e:
        print(f"Error: {e}")

Config valid: 1024MB
Error: Memory limit 128 is outside the allowed range (256-4096).
Error: Mandatory key 'memory_limit_mb' is missing.
Error: Configuration must be a dictionary.


{"memory_limit_mb": 1024}: Passes all checks. Prints "Config valid...". {"memory_limit_mb": 128}: Fails the range check 256 <= 128. A ValueError is raised and caught. {"cpu_cores": 4}: mem_limit is None. A ValueError is raised due to the missing key and caught. "memory_limit_mb: 512": This is a string, not a dictionary. The first isinstance check fails, raising a TypeError which is caught.

Question 3:
Which of the following is the most significant advantage of defining a custom exception hierarchy, such as a base ServiceError with subclasses AuthenticationError and QuotaExceededError?

It allows the calling code to use a single except ServiceError: block to handle all service-related failures, or to use specific except AuthenticationError: blocks for targeted recovery logic.

Correct

This is the primary benefit. A custom hierarchy provides flexibility. Callers can handle errors at different levels of granularity: catch a specific subclass to retry or refresh a token, or catch the base class to perform generic logging and cleanup for any related failure.

Question 4:
A script uses a custom exception hierarchy to manage errors during a file provisioning process. What is the output of this script?

In [6]:
class ProvisionerError(Exception):
    """Base class for provisioning failures."""
    pass
 
class DiskSpaceError(ProvisionerError):
    """Raised when there is not enough disk space."""
    def __init__(self, required, available):
        super().__init__(f"Not enough disk. Required: {required}GB, Available: {available}GB")
 
class PermissionsError(ProvisionerError):
    """Raised due to file system permission issues."""
    pass
 
def provision_file(size_gb, path):
    if size_gb > 100:
        raise DiskSpaceError(required=size_gb, available=100)
    if "/root/" in path:
        raise PermissionsError(f"Cannot write to protected path: {path}")
    print("Provisioning successful.")
 
try:
    provision_file(size_gb=50, path="/root/data.bin")
except DiskSpaceError as e:
    print(f"Caught Disk Error: {e}")
except ProvisionerError as e:
    print(f"Caught Provisioner Error: {e}")
except Exception:
    print("Caught a generic exception.")

Caught Provisioner Error: Cannot write to protected path: /root/data.bin


Correct. The function raises a PermissionsError. The first except block (except DiskSpaceError) does not match. The second except block (except ProvisionerError) does match, because PermissionsError is a subclass of ProvisionerError. Execution enters this block and prints the message.

Question 5:
You are developing a parser for a custom configuration file format. You've created a special exception to handle syntax errors. What will be printed to the console after the following code executes?

In [7]:
class ConfigSyntaxError(ValueError):
    def __init__(self, message, line_num, text):
        full_msg = f"Syntax error on line {line_num}: {message}"
        super().__init__(full_msg)
        self.line = line_num
        self.text = text
 
def parse_config(lines):
    for i, line in enumerate(lines, 1):
        if "=" not in line:
            raise ConfigSyntaxError("Missing '=' assignment", i, line)
    return "Parsed OK"
 
config_text = ["host=server.local", "port", "timeout=30"]
 
try:
    parse_config(config_text)
except ConfigSyntaxError as e:
    print(e)
    print(f"-> Problematic text: '{e.text}'")

Syntax error on line 2: Missing '=' assignment
-> Problematic text: 'port'


Correct. The parse_config function finds that the second line ("port") does not contain an =. It raises a ConfigSyntaxError, passing the message, line number (2), and the text. The except block catches it. The first print(e) prints the message generated by super().__init__(). The second print statement accesses the custom .text attribute on the exception object.

Question 6:
Analyze the following function signature and its internal logic.



def process_data_files(file_paths):
    # (function implementation)


Which of the following implementations best demonstrates the principle of raising an exception for a true error state versus handling a valid-but-empty edge case gracefully?

if not isinstance(file_paths, list):
    raise TypeError("Input must be a list of file paths.")
if not file_paths:
    print("No files to process.")
    return
# ... process files ...
Correct

This implementation correctly identifies two different situations. An input that is not a list is a contract violation (a true error), which is correctly handled by raising a TypeError. An empty list is a valid edge case that is handled gracefully by printing a message and exiting.

## Resource Management with Context Managers

Question 1:
A DevOps script needs to open a log file, write several status updates to it, and ensure the file is always closed, even if a network error interrupts the script mid-operation.

Which of the following two code blocks represents the best practice for this task in Python, and why?

In [ ]:
Block A:

f = open("update.log", "w")
try:
    f.write("Starting...\n")
    # ... network operations that might fail ...
    f.write("Finished.\n")
finally:
    f.close()


Block B:

with open("update.log", "w") as f:
    f.write("Starting...\n")
    # ... network operations that might fail ...
    f.write("Finished.\n")


Block B is better because the with statement is more concise, less error-prone, and guarantees the resource (f) is cleaned up (closed) upon exiting the block for any reason.

Correct

The with statement is the Pythonic best practice for resource management. It encapsulates the try...finally logic, making the code cleaner, more readable, and safer by guaranteeing that the resource's teardown logic (in this case, f.close()) is automatically executed.

Question 2:
A developer writes a custom context manager to temporarily switch the current working directory for a script. However, they notice that if an error occurs during the file operations, the script does not revert to the original directory. What is the primary bug in the temp_directory context manager?

In [ ]:
from contextlib import contextmanager
import os
 
@contextmanager
def temp_directory(path):
    original_dir = os.getcwd()
    os.makedirs(path, exist_ok=True)
    os.chdir(path)
    yield
    os.chdir(original_dir)
    os.rmdir(path)
    print(f"Reverted to {original_dir}")
 
try:
    with temp_directory("./local_temp_folder"):
        print(f"Now in: {os.getcwd()}")
        result = 1 / 0  # Simulate an error
except ZeroDivisionError:
    print("An error occurred.")
 
print(f"Final directory: {os.getcwd()}")


The teardown logic (os.chdir(original_dir)) is not placed inside a finally block, so it is skipped when an exception is raised in the with block.

Correct

Correct. This is the critical bug. When the ZeroDivisionError occurs inside the with block, the generator's execution is terminated. Code that comes after the yield will only be executed if it is in a finally clause. The fix is to wrap the yield in a try...finally block to guarantee the cleanup code runs.

Question 3:
Analyze the following custom context manager class designed to handle database transactions. It is designed to suppress IntegrityError (e.g., duplicate key) while letting other errors propagate. What is the exact output of this script?

In [8]:
class DatabaseTransaction:
    def __enter__(self):
        print("BEGIN TRANSACTION")
        return self
 
    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is None:
            print("COMMIT")
            return False  # Propagate no exception
        elif exc_type is IntegrityError:
            print("ROLLBACK: Ignoring duplicate key.")
            return True  # Suppress this specific exception
        else:
            print("ROLLBACK: An unexpected error occurred.")
            return False  # Propagate other exceptions
 
 
class IntegrityError(Exception):
    pass
 
 
class NetworkError(Exception):
    pass
 
try:
    with DatabaseTransaction():
        raise NetworkError("Connection lost")
except NetworkError as e:
    print(f"Handled at top level: {e}")

BEGIN TRANSACTION
ROLLBACK: An unexpected error occurred.
Handled at top level: Connection lost


Correct. __enter__ is called, printing "BEGIN TRANSACTION". A NetworkError is raised inside the with block. __exit__ is called. exc_type is NetworkError. It doesn't match IntegrityError, so it falls to the else clause, printing "ROLLBACK: An unexpected error occurred.". __exit__ returns False, so the NetworkError is re-raised and propagated outside the with statement. The outer except NetworkError block catches it and prints the final message.

Question 4:
When designing a custom context manager, what is the key difference in purpose between implementing it as a class with __enter__/__exit__ methods versus using the @contextlib.contextmanager decorator on a generator?

The class-based approach is generally better for managing complex state or when the setup/teardown logic is substantial, while the decorator is more suitable for simpler, more linear setup/teardown tasks.

Correct

Correct. This accurately describes the trade-off. A class provides a natural way to manage complex state through its attributes (self). For simple cases like temporarily changing a directory or setting an environment variable, the decorator is more concise and requires less boilerplate.

Question 5:
Considering the following code, what is the purpose of the value returned by the __enter__ method in a class-based context manager?

In [ ]:
class ApiSessionManager:
    def __init__(self, api_key):
        self.key = api_key
        self.session_id = None
 
    def __enter__(self):
        print("Starting API session...")
        self.session_id = "xyz-123"
        return self # Returns the instance itself
 
    def __exit__(self, exc_type, exc_value, traceback):
        print("Closing API session...")
        self.session_id = None
 
with ApiSessionManager("my-secret-key") as session:
    print(f"Using session ID: {session.session_id}")

It is the value that gets assigned to the variable specified in the as clause of the with statement.

Correct

Correct. The with ... as var: syntax captures the return value of the __enter__ method in the variable var. In this example, session becomes a reference to the ApiSessionManager instance, allowing access to its attributes like session_id.

## Python Logging: Core Concepts and Mechanics

Question 1:
A DevOps team is developing a long-running Python service to manage cloud infrastructure. For debugging and auditing, they need to record events such as service startup, configuration reloads, and connection failures. Why is using Python's logging module a better practice than using print() statements for this purpose?


logging allows developers to categorize messages by severity (e.g., DEBUG, INFO, WARNING, ERROR), which can be filtered and routed to different destinations, whereas print() treats all messages with the same importance.

Correct

Correct. This is the core advantage. Log levels allow for granular control over log verbosity. In production, a team might only want to see INFO and above, but in a staging environment, they can enable DEBUG logs for deep diagnostics, all without changing the application code. This is impossible to achieve cleanly with print().

Question 2:
Which log level is most appropriate for recording a user's password during a failed login attempt for debugging purposes?

Passwords and other sensitive credentials should never be logged in plain text, regardless of the log level.

Correct

Correct. This is the fundamental security best practice. Logging sensitive information like passwords, API keys, or personal data creates a major security risk. If you need to confirm a value was received, you can log a confirmation like password_provided: True or a salted hash, but never the raw value.

Question 3:
You are configuring a logger for a script that monitors system metrics. You want to see only high-severity alerts on the console. What will be printed to the console when this script is executed?

In [ ]:
import logging
import sys
 
monitor_logger = logging.getLogger("system.monitor")
monitor_logger.setLevel(logging.INFO)
 
console_handler = logging.StreamHandler(sys.stdout)
console_handler.setLevel(logging.ERROR)
console_handler.setFormatter(logging.Formatter(logging.BASIC_FORMAT))
 
monitor_logger.addHandler(console_handler)
 
monitor_logger.info("CPU usage is at 25%.")
monitor_logger.warning("Memory usage is at 85%.")
monitor_logger.error("Disk space is critically low.")

ERROR:system.monitor:Disk space is critically low.
Correct

Correct. This demonstrates two-stage filtering. The logger's level is INFO, so it accepts INFO, WARNING, and ERROR messages. These messages are passed to the handler. The handler's level is ERROR. It will discard any message with a severity lower than ERROR. Therefore, the INFO and WARNING messages are discarded by the handler, and only the ERROR message is processed and printed.

Question 4:
A junior developer writes a script to log important events. After running it, they see that the audit.log file is created, but it is empty. The expected message "User 'admin' logged in." does not appear in the file. What is the fundamental reason the log message is not written to the file?

In [ ]:
import logging
 
def setup_auditing():
    audit_logger = logging.getLogger("audit_trail")
    audit_logger.setLevel(logging.INFO)
 
    audit_handler = logging.FileHandler("audit.log")
    audit_handler.setLevel(logging.INFO)
 
setup_auditing()
 
logger = logging.getLogger("audit_trail")
logger.info("User 'admin' logged in.")

A logger without any handlers attached to it will not pass log records to any destination. The audit_handler was never attached using audit_logger.addHandler().

Correct

Correct. This is the core issue. A logger's job is to pass log records to its list of handlers. In the code, audit_handler is created but never registered with the audit_logger. Because the logger has no handlers, it effectively discards the log message.

Question 5:
In the architecture of Python's logging module, what are the primary, distinct roles of the Logger, Handler, and Formatter components?

Logger: Provides the main entry point for code to emit messages. Handler: Directs log records to a specific destination. Formatter: Defines the string layout of the final log record.

Correct

Correct. This correctly describes the separation of concerns. Logger: The interface the application code uses (logging.getLogger(...)). Handler: Responsible for the output destination (e.g., StreamHandler for console, FileHandler for files). Formatter: Responsible for the appearance of the log message (e.g., adding a timestamp, level name).